---
version: '3.7'
services:
  scheduler:
    build: ./
    image: karlvr/scheduler
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./crontab-example:/etc/cron.d/crontab-example
    deploy:
      placement:
        constraints:
        - node.role == manager